golang-1.25-linux/1e4dadb8a796a20044e177a108eec65780cd59c308da84f7fdbfdbc758cdf312:
  size: 59768749
  object_id: de462fc6-9995-44f1-7cd0-42d9167dfbec
  sha: sha256:12e6d6a191091ae27dc31f6efc630e3a3b8ba409baf3573d955b196fdf086005
golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: f942d9a7-f769-4fd1-4972-26fc85fb0a76
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-windows/117efdd98cac4d6d362504cddfb6e0926852569d5dd7330479e26c5477b5ada0:
  size: 67448678
  object_id: 9114fbec-449b-4a3f-5d68-e52fe323de58
  sha: sha256:c75e5f4ff62d085cc0017be3ad19d5536f46825fa05db06ec468941f847e3228
golang-1.25-windows/924223df4c326000999e7554ab10919d80de3df3483a2eb60d0494771a9e073c:
  size: 67446385
  object_id: a62e6e75-08b9-4188-495a-4db97a731f70
  sha: sha256:19b4733b727ba5c611b5656187f3ac367d278d64c3d4199a845e39c0fdac5335
golang-1.25-windows/fb4cf863311cceb62a13615813687871d16e7d71f93817ec7b533d6d569e7880:
  size: 67442664
  object_id: 0b77785d-3667-46bf-613b-ab4cbfa4e638
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: 2cceb543-d425-44e4-5b87-1ab85606831e
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
